apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: demo-dns
  namespace: console-demo-resources
  labels:
    app.kubernetes.io/part-of: console-demo-resources
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: demo-gateway
  providerRefs:
    - name: demo-dns-provider-credentials
  loadBalancing:
    geo: US
    defaultGeo: true
    weight: 100
