import * as React from 'react';
import { Card, CardTitle, CardBody, Button } from '@patternfly/react-core';
import {
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  InfoCircleIcon,
  CopyIcon,
} from '@patternfly/react-icons';
import { Link } from 'react-router-dom';
import { STATUS_META } from '../dns/types';
import { TlsRecommendation } from './types';

/**
 * Contextual to-do list generated by the hook. Each recommendation
 * gets a severity dot and, when applicable, either a copyable command
 * or a link to the resource that needs attention. Empty state renders
 * a small "all clear" message.
 */

interface Props {
  recommendations: TlsRecommendation[];
}

const iconFor = (severity: TlsRecommendation['severity']) => {
  switch (severity) {
    case 'critical':
      return <ExclamationCircleIcon style={{ color: STATUS_META.failing.color }} />;
    case 'warning':
      return <ExclamationTriangleIcon style={{ color: STATUS_META.warning.color }} />;
    default:
      return <InfoCircleIcon style={{ color: STATUS_META.unknown.color }} />;
  }
};

async function copyToClipboard(text: string) {
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    // clipboard may be unavailable in cross-origin iframes; fail
    // silently — the operator can still read the command from the
    // detail line.
  }
}

const TLSSmartRecommendations: React.FC<Props> = ({ recommendations }) => (
  <Card aria-label="Smart recommendations" className="rhcl-tls-side-panel">
    <CardTitle>Smart Recommendations</CardTitle>
    <CardBody>
      {recommendations.length === 0 ? (
        <div className="rhcl-tls-empty">Nothing to recommend right now.</div>
      ) : (
        <ol className="rhcl-tls-reco">
          {recommendations.map((r) => (
            <li key={r.id} className={`rhcl-tls-reco-${r.severity}`}>
              <div className="rhcl-tls-reco-head">
                <span className="rhcl-tls-reco-icon">{iconFor(r.severity)}</span>
                <span className="rhcl-tls-reco-title">{r.title}</span>
              </div>
              {r.detail && <div className="rhcl-tls-reco-detail">{r.detail}</div>}
              {r.copyCommand && (
                <div style={{ marginTop: 4 }}>
                  <Button
                    variant="link"
                    isInline
                    icon={<CopyIcon />}
                    onClick={() => copyToClipboard(r.copyCommand!)}
                  >
                    Copy command
                  </Button>
                </div>
              )}
              {r.href && (
                <div style={{ marginTop: 4 }}>
                  <Button
                    variant="link"
                    isInline
                    component={(props) => <Link {...props} to={r.href!} />}
                  >
                    Open resource
                  </Button>
                </div>
              )}
            </li>
          ))}
        </ol>
      )}
    </CardBody>
  </Card>
);

export default TLSSmartRecommendations;
